apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-daemon
  namespace: metrics
  labels:
    app: metrics-daemon
spec:
  selector:
    matchLabels:
      app: metrics-daemon
  template:
    metadata:
      labels:
        app: metrics-daemon
    spec:
      hostNetwork: true
      containers:
      - name: metrics-daemon
        image: 100.109.199.26:30500/metrics_daemon:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: HOST_FILE_PATH_OVERRIDE
          value: "/host/proc/sys/kernel/hostname"
        - name: MEM_FILE_PATH_OVERRIDE
          value: "/host/proc/meminfo"
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      tolerations:
      - effect: NoSchedule
        operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-daemon-service
  namespace: metrics
  labels:
    app: metrics-daemon
spec:
  type: NodePort
  selector:
    app: metrics-daemon
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP